---
title: "STAT 414 - todo for part 3 submittion"
author: "Kyle Nessen, Justin Mai, Aiden Kelly, Arneh Begi"
date: "2024-12-11"
format: pdf
editor: visual
bibliography: references.bib
---

## Introduction

Every fall, monarch butterflies (*Danaus plexippus*) undergo an annual mass migration from their summer breeding grounds across western North America to overwintering groves along the Pacific Coast [@tuskes1978; @Urquhart1978Autumnal]. During winter months, these butterflies "cluster" by the thousands on trees within the groves, often in the same location year after year, despite being those butterflies being generations apart. Scientists hypothesize that monarchs seek out these locations within the groves because they provide ideal weather conditions, including mild temperatures, high humidity, and variable light [@leong1991; @CHAPLIN1982Energy; @weiss1991]. They predict that monarchs will select habitat that meet all of these climatic conditions and will not be found in areas where those conditions are not met, both at the landscape and site levels.

This study investigates how microclimate conditions (temperature, humidity, and light intensity) differ between monarch butterfly aggregation sites and non-aggregation areas within the same grove, seeking to identify whether specific environmental characteristics distinguish the locations where monarchs choose to cluster. 

## Materials and Methods

Our dataset comes from research conducted by Saniee and Dr. Villablanca [@saniee2022]. They directly investigated the "microclimate hypothesis" by taking temperature, humidity, and light measurements at various locations within monarch overwintering habitat. Within each grove, they placed a weather station (array) at a known aggregation site, where monarch butterflies are thought to be selecting favorable weather conditions. From that aggregation site, they placed four additional arrays in a repeated manner to capture variation within the grove (see @fig-samplingDesign). This arrangement of weather arrays was repeated across nine groves in San Luis Obispo, Santa Barbara, and Ventura County (see @fig-siteOverview). Climate measurements were taken every 5 minutes, and derivative summary measures were generated for each day (e.g., minimum, maximum, and average temperature).

![Sampling design relative to the aggregation’s location in the groves. The first sample location was placed in the location of an aggregation (Aggregation). Two more sample locations were placed on the SE and NW edges of each grove relative to the aggregation’s location to capture morning light and prevailing wind (SE edge and NW edge, respectively). Two interior sample locations were placed halfway between the aggregation’s location and the grove’s edge in the NE and SW directions (NE interior and SW interior, respectively).](images/clipboard-521945598.png){#fig-samplingDesign fig-align="center"}

![Nine groves sampled along the California coast in Ventura, Santa Barbara, and San Luis Obispo counties that met study design criteria (see text). The groves from south to north are: Arundell Barranca (V), Harbor Blvd (V), Tecolote Canyon (SB), Hollister Ranch (SB), Spring Canyon Vandenberg Air Force Base (SB), Black Lake (SLO), Oceano Campground (SLO), Pismo Beach State Park (SLO), and Morro Bay Golf Course (SLO).](images/clipboard-4044369441.png){#fig-siteOverview}

## Results

## Discussion
